name: Markdown to Presentation

on:
  push:
    paths:
      - '**/*.md'
  pull_request:
    paths:
      - '**/*.md'

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      UDEV_GOTHIC_URL: https://github.com/yuru7/udev-gothic/releases/download/v2.0.0/UDEVGothic_v2.0.0.zip
      VERSION: null

    steps:
      - uses: actions/checkout@v4
      - name: Extract UDEV Gothic version
        id: extract-version
        run: |
          VERSION=$(echo $UDEV_GOTHIC_URL | grep -oP 'v[0-9]+\.[0-9]+\.[0-9]+')
          echo "VERSION=$VERSION"
          echo "VERSION=$VERSION<<EOF" >> $GITHUB_ENV
      - name: Cache UDEV Gothic font
        id: cache-udev-gothic
        uses: actions/cache@v4
        with:
          path: /usr/share/fonts/truetype/udev-gothic
          key: ${{ runner.os }}-udev-gothic-${{ steps.extract-version.outputs.VERSION }}
          restore-keys: |
            ${{ runner.os }}-udev-gothic-
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
      - name: Install UDEV Gothic font
        if: steps.cache-udev-gothic.outputs.cache-hit != 'true'
        run: |
          wget $UDEV_GOTHIC_URL -O /tmp/UDEVGothic.zip
          unzip /tmp/UDEVGothic.zip -d /tmp/UDEVGothic
          sudo mkdir -p /usr/share/fonts/truetype/udev-gothic
          sudo find /tmp/UDEVGothic -name "*.ttf" -exec cp {} /usr/share/fonts/truetype/udev-gothic/ \;
          sudo fc-cache -fv
      - name: Install Chromium
        id: setup-chrome
        uses: browser-actions/setup-chrome@latest
        with:
          chrome-version: stable
      - name: Install Marp CLI
        run: npm install -g @marp-team/marp-cli
